class AllModelChanges < ActiveRecord::Migration[6.1]
  def change
    change_column :site1_days, :tag0, :string
    change_column :site1_days, :tag1, :string
    change_column :site1_days, :tag2, :string
    change_column :site1_days, :tag3, :string
    change_column :site1_days, :tag4, :string
    change_column :site1_days, :tag5, :string
    change_column :site1_days, :tag6, :string
    change_column :site1_days, :tag7, :string
    change_column :site1_days, :tag8, :string
    change_column :site1_days, :tag9, :string
    change_column :site1_days, :tag10, :string
    change_column :site2_days, :tag0, :string
    change_column :site2_days, :tag1, :string
    change_column :site2_days, :tag2, :string
    change_column :site2_days, :tag3, :string
    change_column :site2_days, :tag4, :string
    change_column :site2_days, :tag5, :string
    change_column :site2_days, :tag6, :string
    change_column :site2_days, :tag7, :string
    change_column :site2_days, :tag8, :string
    change_column :site2_days, :tag9, :string
    change_column :site2_days, :tag10, :string
    change_column :site3_days, :tag0, :string
    change_column :site3_days, :tag1, :string
    change_column :site3_days, :tag2, :string
    change_column :site3_days, :tag3, :string
    change_column :site3_days, :tag4, :string
    change_column :site3_days, :tag5, :string
    change_column :site3_days, :tag6, :string
    change_column :site3_days, :tag7, :string
    change_column :site3_days, :tag8, :string
    change_column :site3_days, :tag9, :string
    change_column :site3_days, :tag10, :string
    change_column :site1_months, :tag0, :string
    change_column :site1_months, :tag1, :string
    change_column :site1_months, :tag2, :string
    change_column :site1_months, :tag3, :string
    change_column :site1_months, :tag4, :string
    change_column :site1_months, :tag5, :string
    change_column :site1_months, :tag6, :string
    change_column :site1_months, :tag7, :string
    change_column :site1_months, :tag8, :string
    change_column :site1_months, :tag9, :string
    change_column :site1_months, :tag10, :string
    change_column :site2_months, :tag0, :string
    change_column :site2_months, :tag1, :string
    change_column :site2_months, :tag2, :string
    change_column :site2_months, :tag3, :string
    change_column :site2_months, :tag4, :string
    change_column :site2_months, :tag5, :string
    change_column :site2_months, :tag6, :string
    change_column :site2_months, :tag7, :string
    change_column :site2_months, :tag8, :string
    change_column :site2_months, :tag9, :string
    change_column :site2_months, :tag10, :string
    change_column :site3_months, :tag0, :string
    change_column :site3_months, :tag1, :string
    change_column :site3_months, :tag2, :string
    change_column :site3_months, :tag3, :string
    change_column :site3_months, :tag4, :string
    change_column :site3_months, :tag5, :string
    change_column :site3_months, :tag6, :string
    change_column :site3_months, :tag7, :string
    change_column :site3_months, :tag8, :string
    change_column :site3_months, :tag9, :string
    change_column :site3_months, :tag10, :string
    change_column :site1_years, :tag0, :string
    change_column :site1_years, :tag1, :string
    change_column :site1_years, :tag2, :string
    change_column :site1_years, :tag3, :string
    change_column :site1_years, :tag4, :string
    change_column :site1_years, :tag5, :string
    change_column :site1_years, :tag6, :string
    change_column :site1_years, :tag7, :string
    change_column :site1_years, :tag8, :string
    change_column :site1_years, :tag9, :string
    change_column :site1_years, :tag10, :string
    change_column :site2_years, :tag0, :string
    change_column :site2_years, :tag1, :string
    change_column :site2_years, :tag2, :string
    change_column :site2_years, :tag3, :string
    change_column :site2_years, :tag4, :string
    change_column :site2_years, :tag5, :string
    change_column :site2_years, :tag6, :string
    change_column :site2_years, :tag7, :string
    change_column :site2_years, :tag8, :string
    change_column :site2_years, :tag9, :string
    change_column :site2_years, :tag10, :string
    change_column :site3_years, :tag0, :string
    change_column :site3_years, :tag1, :string
    change_column :site3_years, :tag2, :string
    change_column :site3_years, :tag3, :string
    change_column :site3_years, :tag4, :string
    change_column :site3_years, :tag5, :string
    change_column :site3_years, :tag6, :string
    change_column :site3_years, :tag7, :string
    change_column :site3_years, :tag8, :string
    change_column :site3_years, :tag9, :string
    change_column :site3_years, :tag10, :string
    change_column :site1_ruikeis, :tag0, :string
    change_column :site1_ruikeis, :tag1, :string
    change_column :site1_ruikeis, :tag2, :string
    change_column :site1_ruikeis, :tag3, :string
    change_column :site1_ruikeis, :tag4, :string
    change_column :site1_ruikeis, :tag5, :string
    change_column :site1_ruikeis, :tag6, :string
    change_column :site1_ruikeis, :tag7, :string
    change_column :site1_ruikeis, :tag8, :string
    change_column :site1_ruikeis, :tag9, :string
    change_column :site1_ruikeis, :tag10, :string
    change_column :site2_ruikeis, :tag0, :string
    change_column :site2_ruikeis, :tag1, :string
    change_column :site2_ruikeis, :tag2, :string
    change_column :site2_ruikeis, :tag3, :string
    change_column :site2_ruikeis, :tag4, :string
    change_column :site2_ruikeis, :tag5, :string
    change_column :site2_ruikeis, :tag6, :string
    change_column :site2_ruikeis, :tag7, :string
    change_column :site2_ruikeis, :tag8, :string
    change_column :site2_ruikeis, :tag9, :string
    change_column :site2_ruikeis, :tag10, :string
    change_column :site3_ruikeis, :tag0, :string
    change_column :site3_ruikeis, :tag1, :string
    change_column :site3_ruikeis, :tag2, :string
    change_column :site3_ruikeis, :tag3, :string
    change_column :site3_ruikeis, :tag4, :string
    change_column :site3_ruikeis, :tag5, :string
    change_column :site3_ruikeis, :tag6, :string
    change_column :site3_ruikeis, :tag7, :string
    change_column :site3_ruikeis, :tag8, :string
    change_column :site3_ruikeis, :tag9, :string
    change_column :site3_ruikeis, :tag10, :string
    rename_column :site1_ruikeis, :points, :point
    rename_column :site2_ruikeis, :points, :point
    rename_column :site3_ruikeis, :points, :point

    
  end
end
